import React, { useState, useEffect, useRef } from 'react';
import { auth, db } from '../services/firebase';
import { collection, query, where, onSnapshot, addDoc, serverTimestamp, Timestamp, doc, writeBatch, limit, orderBy, deleteDoc, setDoc, updateDoc } from 'firebase/firestore';
import { Wallet, TrendingUp, TrendingDown, Receipt, Clock, BarChart3, Plus, ArrowUpRight, ArrowDownLeft, Filter, Search, Calendar, ChevronRight, Trash2, Settings2, Target, Award, Bot, Sparkles, Bell, BellOff, RefreshCcw } from 'lucide-react';
import { useOwner } from '../hooks/useOwner';
import { useToast } from '../components/shared/Toast';

import { useSearchParams } from 'react-router-dom';

const BANKS = [
	'Vietcombank', 'BIDV', 'Agribank', 'VietinBank', 'Techcombank',
	'MBBank', 'VPBank', 'ACB', 'Sacombank', 'TPBank', 'HDBank', 'VIB'
];

const LOAN_TERMS = [
	'3 tháng', '6 tháng', '12 tháng (1 năm)', '24 tháng (2 năm)', '36 tháng (3 năm)', '60 tháng (5 năm)'
];

const Finance = () => {
	const owner = useOwner();
	const { showToast } = useToast();
	const isAdmin = owner.role === 'admin' || owner.accessRights?.finance_view === true;
	const currentUserId = auth.currentUser?.uid;
	const [searchParams, setSearchParams] = useSearchParams();
	const tabParam = searchParams.get('tab') as 'cashbook' | 'aging' | 'profit' | 'performance' | null;
	const [activeTab, setActiveTab] = useState<'cashbook' | 'aging' | 'profit' | 'performance'>(tabParam || 'cashbook');
	const [cashLogs, setCashLogs] = useState<any[]>([]);
	const [orders, setOrders] = useState<any[]>([]);
	const [payments, setPayments] = useState<any[]>([]);
	const [customers, setCustomers] = useState<any[]>([]);
	const [staffs, setStaffs] = useState<any[]>([]);
	const [checkins, setCheckins] = useState<any[]>([]);
	const [products, setProducts] = useState<any[]>([]);
	const [inventoryLogs, setInventoryLogs] = useState<any[]>([]);
	const [attendanceLogs, setAttendanceLogs] = useState<any[]>([]);
	const [kpiPlans, setKpiPlans] = useState<any[]>([]);
	const cashLogsRef = useRef<any[]>([]);
	const [commissionRate, setCommissionRate] = useState(5); // Default 5%
	const [loading, setLoading] = useState(true);
	const [currentPage, setCurrentPage] = useState(1);
	const ITEMS_PER_PAGE = 10;

	// KPI Plan Management
	const [showPlanForm, setShowPlanForm] = useState(false);
	const [selectedStaffForPlan, setSelectedStaffForPlan] = useState<any>(null);
	const [planData, setPlanData] = useState({
		baseSalary: 10000000,
		checkinTarget: 20,
		attendanceTarget: 22,
		newCustomerTarget: 5,
		productTargets: [] as { sku: string, name: string, targetQty: number }[],
		productCommissions: {} as Record<string, number> // { sku: %rate }
	});

	// Filters
	const [fromDate, setFromDate] = useState(() => {
		const now = new Date();
		return new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0];
	});
	const [toDate, setToDate] = useState(() => {
		const now = new Date();
		return new Date(now.getFullYear(), now.getMonth() + 12, 0).toISOString().split('T')[0];
	});
	const [isSendingReminders, setIsSendingReminders] = useState(false);

	// Cashbook Form
	const [showLogForm, setShowLogForm] = useState(searchParams.get('new') === 'true');
	const [logData, setLogData] = useState({
		type: 'chi' as 'thu' | 'chi',
		amount: 0,
		category: 'Vận hành',
		note: '',
		date: new Date().toISOString().split('T')[0],
		interestRate: 0,
		bankName: '',
		loanTerm: '',
		reminderEnabled: false,
		email: '',
		parentId: ''
	});
	const [isFetchingRate, setIsFetchingRate] = useState(false);
	const [selectedNote, setSelectedNote] = useState<string | null>(null);

	// Sync tab with URL
	useEffect(() => {
		if (tabParam && tabParam !== activeTab) {
			setActiveTab(tabParam);
		}
	}, [tabParam]);

	// Redirect non-admins to performance tab
	useEffect(() => {
		if (!owner.loading && !isAdmin && activeTab !== 'performance') {
			setActiveTab('performance');
		}
	}, [owner.loading, isAdmin, activeTab]);

	// Sync modal with URL
	useEffect(() => {
		const isNew = searchParams.get('new') === 'true';
		if (isNew !== showLogForm) {
			setShowLogForm(isNew);
		}
	}, [searchParams]);
	useEffect(() => {
		setCurrentPage(1);
	}, [activeTab, fromDate, toDate]);

	// BOT TỰ ĐỘNG CHẠY NGẦM
	const handleAutoGenerateBankTransactions = async (isManual = true, newLoan: any = null) => {
		const currentLogs = cashLogsRef.current;
		let loans = currentLogs.filter(l =>
			l.type === 'thu' &&
			(l.category === 'Vay ngân hàng' || l.category === 'Vay khác')
		);

		if (newLoan) {
			const exists = loans.some(l => l.id === newLoan.id);
			if (!exists) loans.push(newLoan);
		}

		// Dọn dẹp bản ghi mồ côi (parentId không tồn tại trong loans)
		const orphans = currentLogs.filter(l => 
			l.parentId && 
			l.isAutoGenerated && 
			!loans.some(loan => loan.id === l.parentId)
		);

		const batch = writeBatch(db);
		let count = 0;
		let maxDate = new Date(toDate);

		if (loans.length > 0 && currentLogs.length > 1) {
			for (const orphan of orphans) {
				console.log(`Finance Bot: Cleaning orphan record: ${orphan.note} (ParentID: ${orphan.parentId})`);
				batch.delete(doc(db, 'cash_book', orphan.id));
				count++;
			}
		}

		if (loans.length === 0) return;
		const newAutoRecords: any[] = [];
		const now = new Date();

		for (const loan of loans) {
			const startDate = new Date(loan.date);
			const termMonthsStr = loan.loanTerm.match(/\d+/)?.[0];
			const termMonths = termMonthsStr ? parseInt(termMonthsStr) : 0;
			if (termMonths === 0) continue;

			const maturityEntry = currentLogs.find(l => 
				l.parentId === loan.id && 
				(l.category === 'Nợ gốc ngân hàng' || l.category === 'Đáo hạn ngân hàng')
			);
			
			const monthlyInterest = (loan.amount * (loan.interestRate / 100)) / 12;
			const dailyInterest = monthlyInterest / 30;
			const t0 = loan.createdAt?.toDate() || new Date(); 
			const maturityTime = maturityEntry ? (maturityEntry.createdAt?.toDate() || new Date(maturityEntry.date)) : null;

			for (let i = 1; i <= termMonths; i++) {
				const simulatedDueTime = new Date(startDate);
				simulatedDueTime.setMonth(simulatedDueTime.getMonth() + i);

				// Nếu đã tất toán, không tạo lãi tháng cho thời điểm sau ngày tất toán
				if (maturityTime && simulatedDueTime > maturityTime) break;

				if (now >= simulatedDueTime) {
					const displayDate = new Date(startDate);
					displayDate.setMonth(displayDate.getMonth() + i);
					const dateStr = displayDate.toISOString().split('T')[0];

					const isDuplicate = currentLogs.some(l =>
						l.parentId === loan.id && l.monthIndex === i
					);

					if (!isDuplicate) {
						const interestRef = doc(collection(db, 'cash_book'));
						const interestData = {
							ownerId: owner.ownerId,
							type: 'chi',
							category: 'Lãi suất ngân hàng',
							amount: Math.round(monthlyInterest),
							date: dateStr,
							note: `[Tự động] Lãi vay tháng ${i}/${termMonths} - ${loan.bankName}`,
							parentId: loan.id,
							email: loan.email || '',
							bankName: loan.bankName || '',
							interestRate: loan.interestRate || 0,
							loanTerm: loan.loanTerm || '',
							reminderEnabled: loan.reminderEnabled || false,
							createdAt: new Date(),
							createdBy: currentUserId,
							isAutoGenerated: true,
							monthIndex: i
						};
						batch.set(interestRef, { ...interestData, createdAt: serverTimestamp() });
						newAutoRecords.push(interestData);
						count++;
						const d = new Date(dateStr);
						if (d > maxDate) maxDate = d;
					}

					if (i === termMonths) {
						const isDuplicatePrincipal = currentLogs.filter(l => l.parentId === loan.id).some(l => l.monthIndex === 999);

						if (!isDuplicatePrincipal) {
							const principalRef = doc(collection(db, 'cash_book'));
							const principalData = {
								ownerId: owner.ownerId,
								type: 'chi',
								category: 'Nợ gốc ngân hàng',
								amount: loan.amount,
								date: dateStr,
								note: `[Tự động] Tất toán nợ gốc - ${loan.bankName}`,
								parentId: loan.id,
								email: loan.email || '',
								bankName: loan.bankName || '',
								interestRate: loan.interestRate || 0,
								loanTerm: loan.loanTerm || '',
								reminderEnabled: loan.reminderEnabled || false,
								createdAt: new Date(),
								createdBy: currentUserId,
								isAutoGenerated: true,
								monthIndex: 999
							};
							batch.set(principalRef, { ...principalData, createdAt: serverTimestamp() });
							newAutoRecords.push(principalData);
							count++;
							const d = new Date(dateStr);
							if (d > maxDate) maxDate = d;
						}
					}
				}
			}

			// XỬ LÝ LÃI CUỐI KỲ (CHO CÁC NGÀY LẺ TRƯỚC KHI TẤT TOÁN)
			if (maturityTime && maturityEntry?.category === 'Đáo hạn ngân hàng' && !maturityEntry.isAutoGenerated) {
				const hasFinalInterest = currentLogs.some(l => 
					l.parentId === loan.id && l.isAutoGenerated && l.monthIndex === -1
				);

				if (!hasFinalInterest) {
					// Tính chính xác số ngày lẻ từ khi bắt đầu vay đến khi tất toán
					const diffTime = Math.abs(maturityTime.getTime() - startDate.getTime());
					const totalDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
					
					// Số tháng đầy đủ đã trôi qua
					const fullMonthsPassed = Math.floor(totalDays / 30);
					const oddDays = totalDays % 30;

					if (oddDays > 0) {
						const finalInterest = dailyInterest * oddDays;
						const interestRef = doc(collection(db, 'cash_book'));
						const interestData = {
							ownerId: owner.ownerId,
							type: 'chi',
							category: 'Lãi suất ngân hàng',
							amount: Math.round(finalInterest),
							date: maturityEntry.date,
							note: `[Tự động] Lãi cuối (Lẻ ${oddDays} ngày x ${formatPrice(Math.round(dailyInterest)).replace('₫', '')}) - ${loan.bankName}`,
							parentId: loan.id,
							email: loan.email || '',
							bankName: loan.bankName || '',
							interestRate: loan.interestRate || 0,
							loanTerm: loan.loanTerm || '',
							reminderEnabled: loan.reminderEnabled || false,
							createdAt: new Date(),
							createdBy: currentUserId,
							isAutoGenerated: true,
							monthIndex: -1
						};
						batch.set(interestRef, { ...interestData, createdAt: serverTimestamp() });
						newAutoRecords.push(interestData);
						count++;
					}
				}
			}
		}

		if (count > 0) {
			try {
				await batch.commit();
				console.log(`Finance Bot: Generated ${count} transactions.`);
				
				// Tự động gửi email thông báo cho các bản ghi mới
				for (const record of newAutoRecords) {
					handleBatchSendReminders(record);
				}

				const currentToDateObj = new Date(toDate);
				if (maxDate > currentToDateObj) {
					const newToDateStr = maxDate.toISOString().split('T')[0];
					setToDate(newToDateStr);
				}
				if (isManual) showToast(`Hệ thống đả cập nhật ${count} chứng từ ngân hàng`, "success");
			} catch (error) {
				console.error("Finance Bot: Commit Error", error);
			}
		} else if (isManual) {
			showToast("Dữ liệu đã được cập nhật đầy đủ.", "info");
		}
	};

	const handleAIInterestRate = async () => {
		if (!logData.bankName || !logData.loanTerm) {
			showToast("Vui lòng chọn ngân hàng và kỳ hạn", "info");
			return;
		}

		if (!import.meta.env.VITE_DEEPSEEK_API_KEY) {
			showToast("Chưa cấu hình VITE_DEEPSEEK_API_KEY", "error");
			return;
		}

		setIsFetchingRate(true);
		try {
			const response = await fetch("https://api.deepseek.com/chat/completions", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
					"Authorization": `Bearer ${import.meta.env.VITE_DEEPSEEK_API_KEY}`
				},
				body: JSON.stringify({
					model: "deepseek-chat",
					messages: [
						{
							role: "system",
							content: "Bạn là chuyên gia về thị trường tài chính Việt Nam. Hãy tra cứu và trả về lãi suất VAY KINH DOANH (Business Loan) chính xác cho từng kỳ hạn cụ thể của ngân hàng. Lưu ý: Lãi suất thường thay đổi theo kỳ hạn (3 tháng khác 6 tháng, 12 tháng). Chỉ trả về con số phần trăm."
						},
						{
							role: "user",
							content: `Cập nhật lãi suất VAY KINH DOANH của ngân hàng ${logData.bankName} với kỳ hạn chính xác là ${logData.loanTerm}. Phải trả về con số lãi suất thực tế đang áp dụng cho kỳ hạn này. Chỉ trả về duy nhất con số (ví dụ: 8.2).`
						}
					]
				})
			});

			const data = await response.json();
			const rateText = data.choices?.[0]?.message?.content?.trim() || "";
			const match = rateText.match(/(\d+(\.\d+)?)/);
			const rate = match ? parseFloat(match[0]) : NaN;

			if (!isNaN(rate)) {
				setLogData(prev => ({ ...prev, interestRate: rate }));
				showToast(`DeepSeek: Lãi suất ${logData.bankName} là ${rate}%`, "success");
			}
		} catch (error: any) {
			console.error("DeepSeek Error:", error);
		} finally {
			setIsFetchingRate(false);
		}
	};

	// Auto-fetch interest rate when bank and term are selected
	useEffect(() => {
		if (logData.type === 'thu' && logData.category === 'Vay ngân hàng' && logData.bankName && logData.loanTerm && !isFetchingRate) {
			handleAIInterestRate();
		}
	}, [logData.bankName, logData.loanTerm]);

	useEffect(() => {
		if (owner.loading || !owner.ownerId) return;

		console.log("Finance View: Fetching data for ownerId:", owner.ownerId);

		const qLogs = query(collection(db, 'cash_book'), where('ownerId', '==', owner.ownerId));
		const unsubLogs = onSnapshot(qLogs, (snap) => {
			console.log("Finance: Received cash_book snapshot, count:", snap.size);
			const logs = snap.docs.map(d => ({ id: d.id, ...d.data() }));
			const sortedLogs = logs.sort((a: any, b: any) => {
				const dateA = a.date || '';
				const dateB = b.date || '';
				return dateB.localeCompare(dateA);
			});
			setCashLogs(sortedLogs);
			cashLogsRef.current = sortedLogs;
		}, (err) => {
			console.error("Finance: Firestore CashBook Error:", err);
		});

		const qOrders = query(collection(db, 'orders'), where('ownerId', '==', owner.ownerId));
		const unsubOrders = onSnapshot(qOrders, (snap) => {
			console.log("Finance: Received orders snapshot, count:", snap.size);
			setOrders(snap.docs.map(d => ({ id: d.id, ...d.data() })));
		}, (err) => {
			console.error("Finance: Firestore Orders Error:", err);
		});

		const qPayments = query(collection(db, 'payments'), where('ownerId', '==', owner.ownerId));
		const unsubPayments = onSnapshot(qPayments, (snap) => {
			console.log("Finance: Received payments snapshot, count:", snap.size);
			setPayments(snap.docs.map(d => ({ id: d.id, ...d.data() })));
		}, (err) => {
			console.error("Finance: Firestore Payments Error:", err);
		});

		const qCustomers = query(collection(db, 'customers'), where('ownerId', '==', owner.ownerId));
		const unsubCustomers = onSnapshot(qCustomers, (snap) => {
			console.log("Finance: Received customers snapshot, count:", snap.size);
			setCustomers(snap.docs.map(d => ({ id: d.id, ...d.data() })));
			setLoading(false);
		}, (err) => {
			console.error("Finance: Firestore Customers Error:", err);
			setLoading(false);
		});

		const qStaffs = query(collection(db, 'users'), where('ownerId', '==', owner.ownerId));
		const unsubStaffs = onSnapshot(qStaffs, (snap) => {
			console.log("Finance: Received staffs snapshot, count:", snap.size);
			setStaffs(snap.docs.map(d => ({ id: d.id, ...d.data() })));
		});

		const qCheckins = query(collection(db, 'checkins'), where('ownerId', '==', owner.ownerId));
		const unsubCheckins = onSnapshot(qCheckins, (snap) => {
			setCheckins(snap.docs.map(d => ({ id: d.id, ...d.data() })));
		});

		const qAttendance = query(collection(db, 'attendance_logs'), where('ownerId', '==', owner.ownerId));
		const unsubAttendance = onSnapshot(qAttendance, (snap) => {
			setAttendanceLogs(snap.docs.map(d => ({ id: d.id, ...d.data() })));
		});

		const qProducts = query(collection(db, 'products'), where('ownerId', '==', owner.ownerId));
		const unsubProducts = onSnapshot(qProducts, (snap) => {
			setProducts(snap.docs.map(d => ({ id: d.id, ...d.data() })));
		});

		const qInvLogs = query(collection(db, 'inventory_logs'), where('ownerId', '==', owner.ownerId));
		const unsubInvLogs = onSnapshot(qInvLogs, (snap) => {
			setInventoryLogs(snap.docs.map(d => ({ id: d.id, ...d.data() })));
		});

		const qPlans = query(collection(db, 'kpi_plans'), where('ownerId', '==', owner.ownerId));
		const unsubPlans = onSnapshot(qPlans, (snap) => {
			setKpiPlans(snap.docs.map(d => ({ id: d.id, ...d.data() })));
		});

		return () => {
			unsubLogs();
			unsubOrders();
			unsubPayments();
			unsubCustomers();
			unsubStaffs();
			unsubCheckins();
			unsubAttendance();
			unsubProducts();
			unsubInvLogs();
			unsubPlans();
		};
	}, [owner.loading, owner.ownerId]);

	// BOT TỰ ĐỘNG CHẠY NGẦM
	const isBotRunning = useRef(false);
	useEffect(() => {
		const interval = setInterval(() => {
			if (isBotRunning.current || loading) return;
			isBotRunning.current = true;
			handleAutoGenerateBankTransactions(false).finally(() => {
				isBotRunning.current = false;
			});
		}, 30000); 

		return () => clearInterval(interval);
	}, [owner.ownerId, loading]); 

	const handleAILoanAnalysis = async () => {
		if (!logData.amount || !logData.bankName || !logData.loanTerm || !logData.interestRate) {
			showToast("Vui lòng điền đủ Số tiền, Ngân hàng, Kỳ hạn và Lãi suất để AI phân tích", "info");
			return;
		}

		setIsFetchingRate(true);
		try {
			const response = await fetch("https://api.deepseek.com/chat/completions", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
					"Authorization": `Bearer ${import.meta.env.VITE_DEEPSEEK_API_KEY || ""}`
				},
				body: JSON.stringify({
					model: "deepseek-chat",
					messages: [
						{
							role: "system",
							content: "Bạn là chuyên gia tài chính. Hãy trả về bản tóm tắt CỰC KỲ NGẮN GỌN, vắn tắt, thuần văn bản. KHÔNG định dạng markdown, KHÔNG lời chào, KHÔNG giải thích."
						},
						{
							role: "user",
							content: `Tóm tắt khoản vay (Vắn tắt):
              - Ngân hàng: ${logData.bankName}
              - Gốc: ${new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(logData.amount)}
              - Ngày: ${logData.date}
              - Lãi: ${logData.interestRate}%/năm
              - Kỳ hạn: ${logData.loanTerm}

              Mẫu:
              🏦 Vay [Ngân hàng] gói kinh doanh ngày [Ngày], lãi [Lãi suất]%/năm.
              🕒 Lãi tháng: [Số tiền lãi] | Lãi ngày: [Lãi tháng / 30]
              💰 Đáo hạn ([Kỳ hạn]): [Gốc] + [Lãi cuối] = [Số tiền đáo hạn]
              📈 Tổng nợ (Gốc + Lãi): [Tổng cộng]`
						}
					]
				})
			});

			if (!response.ok) {
				const errorData = await response.json().catch(() => ({}));
				throw new Error(errorData.error?.message || `HTTP error! status: ${response.status}`);
			}

			const data = await response.json();
			if (!data.choices || data.choices.length === 0) {
				throw new Error("Không nhận được phản hồi từ AI");
			}

			const analysis = data.choices[0].message.content.trim();
			setLogData(prev => ({ ...prev, note: analysis }));
			showToast("DeepSeek đã hoàn tất phân tích khoản vay", "success");
		} catch (error: any) {
			console.error("Project AI Analysis Error:", error);
			showToast(`Không thể tạo phân tích AI: ${error.message || 'Lỗi kết nối'}`, "error");
		} finally {
			setIsFetchingRate(false);
		}
	};

	const handleToggleReminder = async (id: string, currentStatus: boolean) => {
		try {
			await updateDoc(doc(db, 'cash_book', id), {
				reminderEnabled: !currentStatus,
				updatedAt: serverTimestamp()
			});
			showToast(`Đã ${!currentStatus ? 'bật' : 'tắt'} nhắc hẹn tất toán (Ngày 25 hàng tháng)`, "success");
		} catch (error) {
			console.error("Finance: Toggle Reminder Error:", error);
			showToast("Lỗi khi cập nhật nhắc hẹn", "error");
		}
	};


	const handleBatchSendReminders = async (specificLog: any = null) => {
		const reminders = specificLog ? [specificLog] : cashLogs.filter(log => log.reminderEnabled === true && log.email);
		
		if (reminders.length === 0) {
			if (!specificLog) showToast("Không có khoản vay nào đang bật chế độ nhắc hẹn.", "info");
			return;
		}

		if (!specificLog && !window.confirm(`Bạn có muốn gửi email nhắc nợ cho ${reminders.length} khoản vay này đến email hệ thống và email khách hàng (nếu có) không?`)) return;

		if (!specificLog) setIsSendingReminders(true);
		let successCount = 0;

		try {
			for (const loan of reminders) {
				try {
					await fetch('https://script.google.com/macros/s/AKfycbwIup8ysoKT4E_g8GOVrBiQxXw7SOtqhLWD2b0GOUT54MuoXgTtxP42XSpFR_3aoXAG7g/exec', {
						method: 'POST',
						mode: 'no-cors',
						headers: { 'Content-Type': 'text/plain;charset=utf-8' },
						body: JSON.stringify({
							action: 'loan_reminder',
							bankName: loan.bankName,
							amount: loan.amount,
							interestRate: loan.interestRate,
							loanTerm: loan.loanTerm,
							date: loan.date,
							clientEmail: loan.email,
							note: loan.note,
							category: loan.category,
							isAutoGenerated: loan.isAutoGenerated || false
						})
					});
					successCount++;
				} catch (err) {
					console.error("Failed to send reminder for:", loan.bankName, err);
				}
			}
			showToast(`Đã gửi ${successCount} thông báo nhắc nợ về email hệ thống thành công!`, "success");
		} catch (error) {
			showToast("Lỗi khi kết nối máy chủ gửi mail", "error");
		} finally {
			setIsSendingReminders(false);
		}
	};


	const handleAddLog = async (e: React.FormEvent) => {
		e.preventDefault();
		if (logData.amount <= 0) return;

		try {
			const docRef = await addDoc(collection(db, 'cash_book'), {
				...logData,
				ownerId: owner.ownerId,
				createdBy: auth.currentUser?.uid,
				createdAt: serverTimestamp()
			});
			console.log("Cash log added successfully, ID:", docRef.id);
			setShowLogForm(false);
			
			// Kích hoạt bot ngay lập tức với ID thật vừa tạo
			if (logData.type === 'thu' && (logData.category === 'Vay ngân hàng' || logData.category === 'Vay khác')) {
				handleAutoGenerateBankTransactions(false, { ...logData, id: docRef.id });
			}

			setLogData({
				type: 'chi',
				amount: 0,
				category: 'Vận hành',
				note: '',
				date: new Date().toISOString().split('T')[0],
				interestRate: 0,
				bankName: '',
				loanTerm: '',
				reminderEnabled: false,
				email: '',
				parentId: ''
			});
			showToast("Ghi sổ quỹ thành công", "success");
		} catch (error) {
			console.error("Error adding cash log:", error);
			showToast("Lỗi khi ghi sổ quỹ", "error");
		}
	};

	const formatPrice = (price: number) => {
		return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price);
	};

	const getPageNumbers = (totalPages: number) => {
		const pages: (number | string)[] = [];
		const radius = 1;

		for (let i = 1; i <= totalPages; i++) {
			if (
				i === 1 ||
				i === totalPages ||
				(i >= currentPage - radius && i <= currentPage + radius) ||
				i <= 3 ||
				i >= totalPages - 2
			) {
				pages.push(i);
			}
		}

		const uniquePages = [...new Set(pages)].sort((a, b) => (a as number) - (b as number));
		const withEllipsis: (number | string)[] = [];

		for (let i = 0; i < uniquePages.length; i++) {
			if (i > 0 && (uniquePages[i] as number) - (uniquePages[i - 1] as number) > 1) {
				withEllipsis.push('...');
			}
			withEllipsis.push(uniquePages[i]);
		}
		return withEllipsis;
	};



	const openKPIDialog = (staff: any) => {
		setSelectedStaffForPlan(staff);
		const existingPlan = kpiPlans.find(p => p.userId === staff.id && p.month === fromDate.slice(0, 7));
		if (existingPlan) {
			setPlanData({
				baseSalary: existingPlan.baseSalary || 10000000,
				checkinTarget: existingPlan.checkinTarget || 20,
				attendanceTarget: existingPlan.attendanceTarget || 22,
				newCustomerTarget: existingPlan.newCustomerTarget || 5,
				productTargets: existingPlan.productTargets || [],
				productCommissions: existingPlan.productCommissions || {}
			});
		} else {
			setPlanData({
				baseSalary: 10000000,
				checkinTarget: 20,
				attendanceTarget: 22,
				newCustomerTarget: 5,
				productTargets: [],
				productCommissions: {}
			});
		}
		setShowPlanForm(true);
	};

	const handleSaveKPIPlan = async () => {
		if (!selectedStaffForPlan) return;
		try {
			const planId = `${selectedStaffForPlan.id}_${fromDate.slice(0, 7)}`;
			await setDoc(doc(db, 'kpi_plans', planId), {
				...planData,
				userId: selectedStaffForPlan.id,
				userEmail: selectedStaffForPlan.email,
				month: fromDate.slice(0, 7),
				ownerId: owner.ownerId,
				updatedAt: serverTimestamp()
			});
			showToast("Đã lưu kế hoạch KPI", "success");
			setShowPlanForm(false);
		} catch (error) {
			console.error("Error saving KPI plan:", error);
			showToast("Lỗi khi lưu kế hoạch", "error");
		}
	};

	if (owner.loading) return null;

	// No longer returning restricted access here, will handle tab-level permissions
	// --- CALCULATIONS ---

	const handleDeleteLog = async (id: string, log: any) => {
		if (!window.confirm(`Bạn có chắc chắn muốn xóa vĩnh viễn ghi chép này: "${log.note || 'Không có tiêu đề'}"?`)) return;

		try {
			await deleteDoc(doc(db, 'cash_book', id));
			
			// Lưu nhật ký hành động (Audit Log)
			try {
				await addDoc(collection(db, 'audit_logs'), {
					action: 'Xóa ghi chép thu chi',
					user: auth.currentUser?.displayName || auth.currentUser?.email || 'Người dùng',
					userId: auth.currentUser?.uid,
					ownerId: owner.ownerId,
					details: `Đã xóa: ${log.type === 'thu' ? '+' : '-'}${formatPrice(log.amount)} - Nội dung: ${log.note || 'Trống'}`,
					createdAt: serverTimestamp()
				});
			} catch (auditErr) {
				console.warn("Audit Log Error:", auditErr);
			}

			showToast("Đã xóa bản ghi thành công", "success");
		} catch (error: any) {
			console.error("Finance Delete Error:", error);
			showToast(`Lỗi: ${error.message}`, "error");
		}
	};

	const filterByDate = (date: any) => {
		if (!date) return false;
		const d = date.seconds ? new Date(date.seconds * 1000).toISOString().split('T')[0] : date;
		return (!fromDate || d >= fromDate) && (!toDate || d <= toDate);
	};

	const filteredLogs = cashLogs.filter(l => filterByDate(l.date));
	const filteredOrders = orders.filter(o => filterByDate(o.orderDate || o.createdAt));
	const filteredPayments = payments.filter(p => filterByDate(p.date || p.createdAt));

	const paginatedLogs = filteredLogs.slice((currentPage - 1) * ITEMS_PER_PAGE, currentPage * ITEMS_PER_PAGE);
	const totalLogsPages = Math.ceil(filteredLogs.length / ITEMS_PER_PAGE);

	// 2. Debt Aging
	const getAgingData = () => {
		const now = toDate ? new Date(toDate) : new Date();
		const agingGroups = {
			under30: [] as any[],
			between30_60: [] as any[],
			between60_90: [] as any[],
			over90: [] as any[]
		};

		customers.forEach(cust => {
			const custOrders = orders.filter(o => o.customerId === cust.id && o.status === 'Đơn chốt');
			const custPayments = payments.filter(p => p.customerId === cust.id);

			const totalBought = custOrders.reduce((s, o) => s + (o.totalAmount || 0), 0);
			const totalPaid = custPayments.reduce((s, p) => s + (p.amount || 0), 0);
			let debt = totalBought - totalPaid;

			if (debt > 0) {
				const sortedOrders = [...custOrders].sort((a, b) => new Date(a.orderDate).getTime() - new Date(b.orderDate).getTime());
				let runningTotal = 0;
				let oldestUnpaidOrder = null;

				for (const o of sortedOrders) {
					runningTotal += (o.totalAmount || 0);
					if (runningTotal > totalPaid) {
						oldestUnpaidOrder = o;
						break;
					}
				}

				if (oldestUnpaidOrder) {
					const orderDate = new Date(oldestUnpaidOrder.orderDate);
					const diffDays = Math.floor((now.getTime() - orderDate.getTime()) / (1000 * 3600 * 24));

					if (diffDays >= 0) {
						const entry = { ...cust, debt, days: diffDays };
						if (diffDays < 30) agingGroups.under30.push(entry);
						else if (diffDays < 60) agingGroups.between30_60.push(entry);
						else if (diffDays < 90) agingGroups.between60_90.push(entry);
						else agingGroups.over90.push(entry);
					}
				}
			}
		});

		return agingGroups;
	};

	const agingData = getAgingData();

	// 3. Profit breakdown
	const orderProfits = filteredOrders.filter(o => o.status === 'Đơn chốt').map(o => {
		const revenue = o.totalAmount || 0;
		const cost = (o.items || []).reduce((sum: number, item: any) => sum + ((Number(item.buyPrice) || 0) * (Number(item.qty) || 0)), 0);
		const profit = revenue - cost - (o.discountValue || 0);
		return { ...o, revenue, cost, profit };
	}).sort((a, b) => new Date(b.orderDate).getTime() - new Date(a.orderDate).getTime());

	// 3. Profitability Totals (Calculated after orderProfits is defined)
	const totalGrossProfit = orderProfits.reduce((sum, o) => sum + (o.profit || 0), 0);
	const totalOperationalExpense = filteredLogs
		.filter(l => l.type === 'chi' && l.category !== 'Nợ gốc ngân hàng' && l.category !== 'Đáo hạn ngân hàng')
		.reduce((sum, l) => sum + (l.amount || 0), 0);
	const netBusinessProfit = totalGrossProfit - totalOperationalExpense;

	const paginatedProfits = orderProfits.slice((currentPage - 1) * ITEMS_PER_PAGE, currentPage * ITEMS_PER_PAGE);
	const totalProfitsPages = Math.ceil(orderProfits.length / ITEMS_PER_PAGE);

	return (
		<div className="min-h-screen bg-[#f8f9fb] dark:bg-slate-950 transition-colors duration-300">
			{/* HEADER */}
			<header className="md:h-20 bg-white dark:bg-slate-900 border-b border-gray-100 dark:border-slate-800 sticky top-0 z-30">
				<div className="h-16 md:h-20 flex items-center justify-between px-4 md:px-8 border-b border-slate-50 dark:border-slate-800/50">
					<div className="flex items-center gap-3">
						<div className="bg-indigo-600 p-2 rounded-xl text-white shadow-lg shadow-indigo-500/20">
							<Wallet size={20} />
						</div>
						<h2 className="text-lg md:text-xl font-black text-[#1A237E] dark:text-indigo-400 uppercase tracking-tight">Quản Lý Tài Chính</h2>
					</div>

					<div className="flex bg-slate-100/50 dark:bg-slate-800/50 p-1.5 rounded-2xl border border-slate-100/50 dark:border-slate-800/50 overflow-x-auto no-scrollbar touch-pan-x shrink-0 max-w-[calc(100vw-180px)] md:max-w-none">
						{isAdmin && (
							<>
								<button
									onClick={() => setActiveTab('cashbook')}
									className={`px-6 py-2 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${activeTab === 'cashbook' ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
									Sổ Quỹ
								</button>
								<button
									onClick={() => setActiveTab('aging')}
									className={`px-6 py-2 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${activeTab === 'aging' ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
									Tuổi Nợ
								</button>
								<button
									onClick={() => setActiveTab('profit')}
									className={`px-6 py-2 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${activeTab === 'profit' ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
									Lợi Nhuận
								</button>
							</>
						)}
						<button
							onClick={() => setActiveTab('performance')}
							className={`px-4 md:px-6 py-2 rounded-xl text-[10px] md:text-xs font-black uppercase tracking-widest transition-all whitespace-nowrap ${activeTab === 'performance' ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-400 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
							{isAdmin ? 'KPI Đội Ngũ' : 'KPI Cá Nhân'}
						</button>
					</div>
				</div>

				{/* Filter Bar */}
				<div className="px-4 md:px-8 py-3 bg-slate-50/50 dark:bg-slate-900/50 backdrop-blur-md flex flex-wrap items-center gap-4">
					<div className="flex items-center gap-3 bg-white dark:bg-slate-800 px-4 py-2 rounded-2xl border border-slate-100 dark:border-slate-800 shadow-sm">
						<Calendar size={16} className="text-indigo-500" />
						<div className="flex items-center gap-2">
							<input
								type="date"
								className="bg-transparent border-none p-0 text-xs font-black uppercase text-slate-700 dark:text-slate-200 focus:ring-0"
								value={fromDate}
								onChange={(e) => setFromDate(e.target.value)}
							/>
							<span className="text-slate-300 font-bold">→</span>
							<input
								type="date"
								className="bg-transparent border-none p-0 text-xs font-black uppercase text-slate-700 dark:text-slate-200 focus:ring-0"
								value={toDate}
								onChange={(e) => setToDate(e.target.value)}
							/>
						</div>
					</div>
					<div className="text-[10px] font-black text-slate-400 uppercase tracking-[2px] hidden lg:block opacity-60">
						Lọc dữ liệu theo thời gian
					</div>
				</div>
			</header>

			<main className="p-4 md:p-8 max-w-[1400px] mx-auto">

				{activeTab === 'cashbook' && (
					<div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
						{/* Overview Cards */}
						<div className="grid grid-cols-1 md:grid-cols-3 gap-6">
							<div className="bg-white dark:bg-slate-900 p-6 rounded-[2rem] border border-slate-100 dark:border-slate-800 shadow-sm">
								<p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Lợi nhuận gộp bán hàng</p>
								<div className="flex items-center justify-between">
									<h3 className="text-2xl font-black text-emerald-600 dark:text-emerald-400 tracking-tighter">{formatPrice(totalGrossProfit)}</h3>
									<div className="bg-emerald-50 dark:bg-emerald-900/20 p-2 rounded-lg text-emerald-600"><TrendingUp size={20} /></div>
								</div>
								<p className="text-[9px] font-bold text-slate-400 mt-2 uppercase tracking-tight italic opacity-70">Tổng lãi từ các đơn hàng đã chốt</p>
							</div>
							<div className="bg-white dark:bg-slate-900 p-6 rounded-[2rem] border border-slate-100 dark:border-slate-800 shadow-sm">
								<p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Chi phí (Vận hành & Lãi)</p>
								<div className="flex items-center justify-between">
									<h3 className="text-2xl font-black text-rose-600 dark:text-rose-400 tracking-tighter">{formatPrice(totalOperationalExpense)}</h3>
									<div className="bg-rose-50 dark:bg-rose-900/20 p-2 rounded-lg text-rose-600"><ArrowDownLeft size={20} /></div>
								</div>
								<p className="text-[9px] font-bold text-slate-400 mt-2 uppercase tracking-tight italic opacity-70">Tổng phí vận hành & lãi suất tiền vay</p>
							</div>
							<div className="bg-indigo-600 dark:bg-indigo-900 p-6 rounded-[2rem] shadow-xl shadow-indigo-500/20 text-white relative overflow-hidden">
								<div className="absolute -right-4 -bottom-4 w-24 h-24 bg-white/10 rounded-full blur-2xl"></div>
								<p className="text-[10px] font-black text-white/60 uppercase tracking-widest mb-2">Lợi nhuận ròng thực tế</p>
								<div className="flex items-center justify-between">
									<h3 className="text-2xl font-black tracking-tighter">{formatPrice(netBusinessProfit)}</h3>
									<Sparkles size={24} className="text-white/40" />
								</div>
								<p className="text-[9px] font-bold text-white/50 mt-2 uppercase tracking-tight italic">Lợi nhuận cuối cùng sau khi trừ mọi chi phí</p>
							</div>
						</div>

						{/* Log List */}
						<div className="bg-white dark:bg-slate-900 rounded-[2rem] border border-slate-100 dark:border-slate-800 shadow-sm overflow-hidden text-sm">
							<div className="p-6 border-b border-slate-50 dark:border-slate-800 flex flex-wrap gap-4 justify-between items-center">
								<h3 className="font-black text-slate-900 dark:text-white uppercase tracking-tight">Nhật ký thu chi nội bộ</h3>
								<div className="flex items-center gap-3">
									<button
										onClick={handleBatchSendReminders}
										disabled={isSendingReminders}
										className="bg-amber-500 hover:bg-amber-600 text-white px-4 py-2 rounded-xl font-bold flex items-center gap-2 transition-all active:scale-95 text-xs uppercase tracking-tight disabled:opacity-50"
										title="Gửi nhắc nợ hàng tháng cho các khoản vay đang bật chuông"
									>
										{isSendingReminders ? <RefreshCcw size={18} className="animate-spin" /> : <Bell size={18} />}
										Nhắc nợ
									</button>
									<button
										onClick={() => setShowLogForm(true)}
										className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-xl font-bold flex items-center gap-2 transition-all active:scale-95 text-xs uppercase tracking-tight"
									>
										<Plus size={18} /> Ghi chú Thu/Chi
									</button>
								</div>
							</div>
							<div className="md:hidden p-4 space-y-4">
								{paginatedLogs.length === 0 ? (
									<div className="text-center py-10 text-slate-400 italic">
										Chưa có ghi chép thu chi nào cho kỳ này.
									</div>
								) : (
									paginatedLogs.map(log => (
										<div key={log.id} className="bg-white dark:bg-slate-900 p-4 rounded-[1.5rem] border border-slate-100 dark:border-slate-800 shadow-sm space-y-3 relative overflow-hidden">
											<div className="flex justify-between items-start">
												<div className="space-y-1">
													<span className={`px-2 py-0.5 rounded-full text-[10px] font-black uppercase ${log.type === 'thu' ? 'bg-emerald-50 text-emerald-600' : 'bg-rose-50 text-rose-600'}`}>
														{log.category}
													</span>
													<p className="text-[10px] text-slate-400 font-bold">{log.date}</p>
												</div>
												<div className="text-right">
													<p className={`text-lg font-black tracking-tighter ${log.type === 'thu' ? 'text-emerald-600' : 'text-rose-600'}`}>
														{log.type === 'thu' ? '+' : '-'}{formatPrice(log.amount)}
													</p>
												</div>
											</div>
											
											<div className="space-y-2 cursor-pointer active:opacity-70" onClick={() => setSelectedNote(log.note)}>
												<p className="text-sm font-medium text-slate-700 dark:text-slate-300 leading-snug line-clamp-3">
													{log.note}
												</p>
												{log.email && (
													<p className="text-[10px] text-indigo-500 italic font-medium flex items-center gap-1">
														<span className="material-symbols-outlined text-[12px]">mail</span> {log.email}
													</p>
												)}
												{log.bankName && (
													<div className="bg-slate-50 dark:bg-slate-800/50 p-2 rounded-xl border border-slate-100 dark:border-slate-700/50">
														<p className="text-[9px] text-slate-500 font-black uppercase flex items-center gap-1">
															<Sparkles size={10} className="text-indigo-400" /> {log.bankName}
														</p>
														<p className="text-[8px] text-slate-400 font-medium">Lãi: {log.interestRate}% - {log.loanTerm}</p>
													</div>
												)}
											</div>

											<div className="pt-3 border-t border-slate-50 dark:border-slate-800 flex justify-between items-center">
												<div className="flex items-center gap-2">
													{log.parentId ? (
														<span className="text-[10px] font-black text-indigo-600 bg-indigo-50 dark:bg-indigo-900/20 px-2 py-1 rounded-lg">
															ID: #{log.parentId.slice(-6).toUpperCase()}
														</span>
													) : (log.category === 'Vay ngân hàng' || log.category === 'Vay khác') ? (
														<span className="text-[10px] font-black text-emerald-600 bg-emerald-50 dark:bg-emerald-900/20 px-2 py-1 rounded-lg">
															ID: #{log.id.slice(-6).toUpperCase()}
														</span>
													) : (
														<span className="text-[8px] text-slate-300 font-bold uppercase opacity-30">Chi phí lẻ</span>
													)}
												</div>
												<button
													type="button"
													onClick={() => handleDeleteLog(log.id, log)}
													className="flex items-center gap-1 ps-3 pe-2 py-1.5 bg-rose-50 text-rose-600 rounded-xl text-[10px] font-black uppercase active:scale-95 transition-transform"
												>
													Xoá <Trash2 size={12} />
												</button>
											</div>
										</div>
									))
								)}
							</div>

							<div className="hidden md:block overflow-x-auto">
								<table className="w-full text-left">
									<thead className="bg-slate-50 dark:bg-slate-800/50 text-[10px] font-black text-slate-400 uppercase tracking-widest">
										<tr>
											<th className="px-6 py-4 hidden md:table-cell">Ngày</th>
											<th className="px-6 py-4">Phân loại</th>
											<th className="px-6 py-4">Nội dung</th>
											<th className="px-6 py-4 hidden sm:table-cell">Email</th>
											<th className="px-6 py-4 text-right">Số tiền</th>
											<th className="px-6 py-4 text-center hidden md:table-cell">Mã Khoản Vay</th>
											<th className="px-6 py-4 text-right">Thao tác</th>
										</tr>
									</thead>
									<tbody className="divide-y divide-slate-50 dark:divide-slate-800">
										{paginatedLogs.length === 0 ? (
											<tr>
												<td colSpan={7} className="px-6 py-10 text-center text-slate-400 italic">
													Chưa có ghi chép thu chi nào cho kỳ này.
												</td>
											</tr>
										) : (
											paginatedLogs.map(log => (
												<tr key={log.id} className="hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
													<td className="px-6 py-4 text-xs font-bold text-slate-500 whitespace-nowrap hidden md:table-cell">
														{log.date}
													</td>
													<td className="px-6 py-4 text-center">
														<span className={`px-2 py-0.5 rounded-full text-[9px] font-black uppercase inline-block ${log.category === 'Vay ngân hàng' || log.type === 'thu'
															? 'bg-emerald-50 text-emerald-600 dark:bg-emerald-900/20'
															: log.category === 'Vận hành'
																? 'bg-blue-50 text-blue-600 dark:bg-blue-900/20'
																: 'bg-orange-50 text-orange-600 dark:bg-orange-900/20'
															}`}>
															{log.category}
														</span>
													</td>
													<td className="px-6 py-4 cursor-pointer hover:bg-slate-100/50 dark:hover:bg-slate-700/30 transition-colors" onClick={() => setSelectedNote(log.note)}>
														<div className="flex flex-col">
															<span className="font-medium text-slate-700 dark:text-slate-300 text-xs sm:text-sm line-clamp-1">{log.note}</span>
															{log.bankName && (
																<span className="text-[9px] text-slate-400 font-bold uppercase tracking-tight flex items-center gap-1 mt-0.5">
																	<Sparkles size={10} className="text-indigo-400" /> {log.bankName}
																</span>
															)}
														</div>
													</td>
													<td className="px-6 py-4 text-xs text-slate-500 font-medium hidden sm:table-cell">
														{log.email || '--'}
													</td>
													<td className={`px-6 py-4 text-right font-black text-sm ${log.type === 'thu' ? 'text-emerald-600' : 'text-rose-600'}`}>
														{log.type === 'thu' ? '+' : '-'}{formatPrice(log.amount)}
													</td>
													<td className="px-6 py-4 text-center hidden md:table-cell">
														{log.parentId ? (
															<span className="text-[10px] font-black text-indigo-600 bg-indigo-50 dark:bg-indigo-900/20 px-2 py-1 rounded-lg">
																#{log.parentId.slice(-6).toUpperCase()}
															</span>
														) : (log.category === 'Vay ngân hàng' || log.category === 'Vay khác') ? (
															<span className="text-[10px] font-black text-emerald-600 bg-emerald-50 dark:bg-emerald-900/20 px-2 py-1 rounded-lg">
																#{log.id.slice(-6).toUpperCase()}
															</span>
														) : (
															<span className="text-[8px] text-slate-300 font-bold uppercase opacity-30">--</span>
														)}
													</td>
													<td className="px-6 py-4 text-right">
														<button
															type="button"
															onClick={() => handleDeleteLog(log.id, log)}
															className="size-9 flex items-center justify-center text-slate-300 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-900/20 rounded-xl transition-all active:scale-95 cursor-pointer relative z-10"
															title="Xóa ghi chép"
														>
															<Trash2 size={16} />
														</button>
													</td>
												</tr>
											))
										)}
									</tbody>
								</table>
							</div>
						</div>

						{/* Pagination UI - Cash Logs */}
						{totalLogsPages > 1 && (
							<div className="flex flex-col md:flex-row items-center justify-between gap-4 bg-white dark:bg-slate-900 p-4 rounded-2xl border border-slate-100 dark:border-slate-800 transition-colors">
								<p className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-2">
									Hiển thị {(currentPage - 1) * ITEMS_PER_PAGE + 1} - {Math.min(currentPage * ITEMS_PER_PAGE, filteredLogs.length)} của {filteredLogs.length} ghi chép
								</p>
								<div className="flex items-center gap-2">
									<button
										disabled={currentPage === 1}
										onClick={() => { setCurrentPage(prev => prev - 1); window.scrollTo(0, 0); }}
										className="size-10 flex items-center justify-center rounded-xl bg-slate-50 dark:bg-slate-800 text-slate-500 disabled:opacity-30 transition-all hover:bg-slate-100 dark:hover:bg-slate-700"
									>
										<ChevronRight className="rotate-180" size={18} />
									</button>
									<div className="flex items-center gap-1">
										{getPageNumbers(totalLogsPages).map((page, idx) => (
											<button
												key={idx}
												onClick={() => typeof page === 'number' && setCurrentPage(page)}
												disabled={page === '...'}
												className={`size-10 rounded-xl font-black text-xs transition-all ${page === currentPage
													? 'bg-[#1A237E] text-white shadow-lg shadow-blue-500/20'
													: page === '...'
														? 'text-slate-400 cursor-default'
														: 'bg-slate-50 dark:bg-slate-800 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700'
													}`}
											>
												{page}
											</button>
										))}
									</div>
									<button
										disabled={currentPage === totalLogsPages}
										onClick={() => { setCurrentPage(prev => prev + 1); window.scrollTo(0, 0); }}
										className="size-10 flex items-center justify-center rounded-xl bg-slate-50 dark:bg-slate-800 text-slate-500 disabled:opacity-30 transition-all hover:bg-slate-100 dark:hover:bg-slate-700"
									>
										<ChevronRight size={18} />
									</button>
								</div>
							</div>
						)}
					</div>
				)}

				{activeTab === 'aging' && (
					<div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
						<div className="grid grid-cols-1 md:grid-cols-4 gap-4">
							{[
								{ label: '< 30 Ngày', data: agingData.under30, color: 'emerald' },
								{ label: '30 - 60 Ngày', data: agingData.between30_60, color: 'blue' },
								{ label: '60 - 90 Ngày', data: agingData.between60_90, color: 'orange' },
								{ label: '> 90 Ngày', data: agingData.over90, color: 'rose' }
							].map((group, i) => (
								<div key={i} className={`bg-white dark:bg-slate-900 p-6 rounded-[2rem] border-l-4 border-${group.color}-500 shadow-sm`}>
									<p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{group.label}</p>
									<h4 className="text-2xl font-black text-slate-800 dark:text-white">{group.data.length} <span className="text-xs text-slate-400">Khách hàng</span></h4>
									<p className={`text-xs font-bold text-${group.color}-600 mt-2`}>
										Nợ: {formatPrice(group.data.reduce((s, c) => s + c.debt, 0))}
									</p>
								</div>
							))}
						</div>

						<div className="bg-white dark:bg-slate-900 rounded-[2rem] border border-slate-100 dark:border-slate-800 shadow-sm overflow-hidden">
							<div className="p-6 border-b border-slate-50 dark:border-slate-800">
								<h3 className="font-black text-slate-900 dark:text-white uppercase tracking-tight">Chi tiết nợ quá hạn</h3>
							</div>
							<div className="divide-y divide-slate-50 dark:divide-slate-800">
								{Object.entries(agingData).flatMap(([key, list]) => list).sort((a, b) => b.days - a.days).map((item, i) => (
									<div key={i} className="p-6 flex items-center justify-between hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
										<div className="flex items-center gap-4">
											<div className={`size-12 rounded-2xl flex items-center justify-center font-black text-white shadow-lg ${item.days > 90 ? 'bg-rose-500' : item.days > 60 ? 'bg-orange-500' : 'bg-indigo-500'}`}>
												{item.name?.[0] || 'K'}
											</div>
											<div>
												<h4 className="text-sm font-black text-slate-800 dark:text-white uppercase tracking-tight">{item.name}</h4>
												<p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest flex items-center gap-1 mt-1">
													<Clock size={10} /> Quá hạn {item.days} ngày
												</p>
											</div>
										</div>
										<div className="text-right">
											<p className="text-sm font-black text-rose-600 tracking-tight">{formatPrice(item.debt)}</p>
											<button className="text-[10px] font-black text-indigo-600 uppercase tracking-widest mt-1 hover:underline">Nhắc nợ ngay</button>
										</div>
									</div>
								))}
							</div>
						</div>
					</div>
				)}

				{activeTab === 'profit' && (
					<div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
						<div className="bg-indigo-600 p-8 rounded-[2.5rem] shadow-xl shadow-indigo-500/20 text-white relative overflow-hidden">
							<div className="absolute right-0 top-0 w-64 h-64 bg-white/5 rounded-full blur-3xl -mr-20 -mt-20"></div>
							<div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative z-10">
								<div>
									<p className="text-white/60 text-[10px] font-black uppercase tracking-widest mb-2">Tổng doanh thu chốt</p>
									<p className="text-3xl font-black tracking-tighter">{formatPrice(orderProfits.reduce((s, o) => s + o.revenue, 0))}</p>
								</div>
								<div>
									<p className="text-white/60 text-[10px] font-black uppercase tracking-widest mb-2">Tổng giá vốn nhập</p>
									<p className="text-3xl font-black tracking-tighter text-white/40">{formatPrice(orderProfits.reduce((s, o) => s + o.cost, 0))}</p>
								</div>
								<div>
									<p className="text-orange-400 text-[10px] font-black uppercase tracking-widest mb-2">Lợi nhuận gộp</p>
									<div className="flex items-center gap-3">
										<p className="text-3xl font-black text-white tracking-tighter">{formatPrice(orderProfits.reduce((s, o) => s + o.profit, 0))}</p>
										<div className="bg-white/10 px-2 py-1 rounded text-[10px] font-black">
											{((orderProfits.reduce((s, o) => s + o.profit, 0) / (orderProfits.reduce((s, o) => s + o.revenue, 0) || 1)) * 100).toFixed(1)}%
										</div>
									</div>
								</div>
							</div>
						</div>

						<div className="bg-white dark:bg-slate-900 rounded-[2rem] border border-slate-100 dark:border-slate-800 shadow-sm overflow-hidden">
							<div className="p-6 border-b border-slate-50 dark:border-slate-800 flex justify-between items-center">
								<h3 className="font-black text-slate-900 dark:text-white uppercase tracking-tight">Chi tiết lợi nhuận từng đơn</h3>
								<div className="flex items-center gap-2 bg-slate-50 dark:bg-slate-800 px-4 py-2 rounded-xl text-xs font-black text-slate-500">
									<BarChart3 size={16} /> Xếp hạng lợi nhuận
								</div>
							</div>
							<div className="overflow-x-auto">
								<table className="w-full text-left text-sm">
									<thead className="bg-slate-50 dark:bg-slate-800/50 text-[10px] font-black text-slate-400 uppercase tracking-widest">
										<tr>
											<th className="px-6 py-4">Đơn hàng</th>
											<th className="px-6 py-4">Khách hàng</th>
											<th className="px-6 py-4 text-right">Doanh thu</th>
											<th className="px-6 py-4 text-right">Giá vốn</th>
											<th className="px-6 py-4 text-right">Lợi nhuận</th>
										</tr>
									</thead>
									<tbody className="divide-y divide-slate-50 dark:divide-slate-800">
										{paginatedProfits.map((order, i) => (
											<tr key={i} className="hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
												<td className="px-6 py-4 font-black text-slate-900 dark:text-indigo-400">{order.invoiceId || order.id.slice(-6).toUpperCase()}</td>
												<td className="px-6 py-4 font-bold text-slate-600 dark:text-slate-400">{order.customerName}</td>
												<td className="px-6 py-4 text-right font-bold text-slate-700 dark:text-slate-300">{formatPrice(order.revenue)}</td>
												<td className="px-6 py-4 text-right text-slate-400 italic">{formatPrice(order.cost)}</td>
												<td className="px-6 py-4 text-right">
													<span className={`px-2 py-1 rounded-lg font-black ${order.profit > 0 ? 'bg-emerald-50 text-emerald-600 dark:bg-emerald-900/20' : 'bg-rose-50 text-rose-600 dark:bg-rose-900/20'}`}>
														{formatPrice(order.profit)}
													</span>
												</td>
											</tr>
										))}
									</tbody>
								</table>
							</div>
						</div>

						{/* Pagination UI - Profits */}
						{totalProfitsPages > 1 && (
							<div className="flex flex-col md:flex-row items-center justify-between gap-4 bg-white dark:bg-slate-900 p-4 rounded-2xl border border-slate-100 dark:border-slate-800 transition-colors">
								<p className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-2">
									Hiển thị {(currentPage - 1) * ITEMS_PER_PAGE + 1} - {Math.min(currentPage * ITEMS_PER_PAGE, orderProfits.length)} của {orderProfits.length} đơn
								</p>
								<div className="flex items-center gap-2">
									<button
										disabled={currentPage === 1}
										onClick={() => { setCurrentPage(prev => prev - 1); window.scrollTo(0, 0); }}
										className="size-10 flex items-center justify-center rounded-xl bg-slate-50 dark:bg-slate-800 text-slate-500 disabled:opacity-30 transition-all hover:bg-slate-100 dark:hover:bg-slate-700"
									>
										<ChevronRight className="rotate-180" size={18} />
									</button>
									<div className="flex items-center gap-1">
										{getPageNumbers(totalProfitsPages).map((page, idx) => (
											<button
												key={idx}
												onClick={() => typeof page === 'number' && setCurrentPage(page)}
												disabled={page === '...'}
												className={`size-10 rounded-xl font-black text-xs transition-all ${page === currentPage
													? 'bg-[#1A237E] text-white shadow-lg shadow-blue-500/20'
													: page === '...'
														? 'text-slate-400 cursor-default'
														: 'bg-slate-50 dark:bg-slate-800 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700'
													}`}
											>
												{page}
											</button>
										))}
									</div>
									<button
										disabled={currentPage === totalProfitsPages}
										onClick={() => { setCurrentPage(prev => prev + 1); window.scrollTo(0, 0); }}
										className="size-10 flex items-center justify-center rounded-xl bg-slate-50 dark:bg-slate-800 text-slate-500 disabled:opacity-30 transition-all hover:bg-slate-100 dark:hover:bg-slate-700"
									>
										<ChevronRight size={18} />
									</button>
								</div>
							</div>
						)}
					</div>
				)}

				{activeTab === 'performance' && (
					<div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
						{/* Enhanced Header Cards */}
						<div className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-100 dark:border-slate-800 shadow-sm overflow-hidden p-8 mb-8">
							<div className="flex items-center gap-6 mb-8">
								<div className="size-12 md:size-16 bg-indigo-50 dark:bg-indigo-900/40 rounded-[1.2rem] md:rounded-[1.5rem] flex items-center justify-center text-indigo-600 shadow-inner">
									<TrendingUp size={24} className="md:w-8 md:h-8" />
								</div>
								<div>
									<h3 className="text-lg md:text-2xl font-black text-[#1A237E] dark:text-indigo-400 uppercase tracking-tight">
										{isAdmin ? 'Thống kê hiệu suất đội ngũ' : 'Hiệu suất cá nhân của bạn'}
									</h3>
									<p className="text-[8px] md:text-[10px] font-black text-slate-400 uppercase tracking-[2px] mt-1">Sơ đồ hoa hồng & Hoạt động thực tế</p>
								</div>
							</div>

							<div className="grid grid-cols-1 md:grid-cols-4 gap-6">
								<div className="bg-[#f8f9ff] dark:bg-slate-800/40 p-6 rounded-[2rem] border border-indigo-50/50 dark:border-slate-700/30">
									<p className="text-[9px] font-black text-indigo-400 uppercase tracking-widest mb-3">
										{isAdmin ? 'Top Sales' : 'Cấp bậc'}
									</p>
									<p className="text-lg font-black text-slate-900 dark:text-white uppercase leading-none">
										{isAdmin ? (
											staffs.map(s => {
												const userOrders = filteredOrders.filter(o => o.createdBy === s.id && o.status === 'Đơn chốt');
												return { name: s.displayName || s.email, total: userOrders.reduce((sum, o) => sum + (o.totalAmount || 0), 0) };
											}).sort((a, b) => b.total - a.total)[0]?.name || '--'
										) : 'Nhân viên kinh doanh'}
									</p>
								</div>
								<div className="bg-[#f8f9ff] dark:bg-slate-800/40 p-6 rounded-[2rem] border border-indigo-50/50 dark:border-slate-700/30">
									<p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-3">Tổng hoạt động</p>
									<p className="text-lg font-black text-slate-900 dark:text-white uppercase leading-none">
										{isAdmin ? checkins.filter(c => filterByDate(c.createdAt)).length : checkins.filter(c => c.userId === currentUserId && filterByDate(c.createdAt)).length}
										<span className="text-[10px] text-slate-400 font-bold ml-1">Lượt</span>
									</p>
								</div>
								<div className="bg-[#f8f9ff] dark:bg-slate-800/40 p-6 rounded-[2rem] border border-indigo-50/50 dark:border-slate-700/30">
									<p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-3">Đơn chốt</p>
									<p className="text-lg font-black text-slate-900 dark:text-white uppercase leading-none">
										{isAdmin ? filteredOrders.filter(o => o.status === 'Đơn chốt').length : filteredOrders.filter(o => o.createdBy === currentUserId && o.status === 'Đơn chốt').length}
										<span className="text-[10px] text-slate-400 font-bold ml-1">Đơn</span>
									</p>
								</div>
								<div className="bg-amber-50 dark:bg-amber-900/10 p-6 rounded-[2rem] border border-amber-100/50 dark:border-amber-900/20">
									<p className="text-[9px] font-black text-amber-500 uppercase tracking-widest mb-3">Hoa hồng dự kiến</p>
									<p className="text-lg font-black text-amber-600 leading-none">
										{(() => {
											let totalCom = 0;
											const targetStaffs = staffs.filter(s => isAdmin || s.id === currentUserId);
											targetStaffs.forEach(s => {
												const staffOrders = filteredOrders.filter(o => o.createdBy === s.id && o.status === 'Đơn chốt');
												const plan = kpiPlans.find(p => p.userId === s.id && p.month === fromDate.slice(0, 7));
												staffOrders.forEach(o => {
													(o.items || []).forEach((item: any) => {
														const sku = item.sku || products.find(p => p.id === item.id)?.sku || 'N/A';
														const key = sku !== 'N/A' ? sku : item.name;
														const pData = products.find(p => (sku && p.sku === sku) || (item.id && p.id === item.id));
														const buyPrice = Number(item.buyPrice || pData?.priceBuy || 0);
														const avgPrice = Number(item.price) || 0;
														const profit = (avgPrice - buyPrice) * (Number(item.qty) || 0);
														const rate = plan?.productCommissions?.[key] || 0;
														totalCom += profit * (rate / 100);
													});
												});
											});
											return formatPrice(totalCom);
										})()}
									</p>
								</div>
							</div>
						</div>

						{/* Table 1: Bảng tính hoa hồng theo sản phẩm */}
						<div className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-100 dark:border-slate-800 shadow-sm overflow-hidden mb-8">
							<div className="p-8 border-b border-slate-50 dark:border-slate-800 flex justify-between items-center">
								<div>
									<h3 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-tight">Chi tiết hoa hồng theo sản phẩm</h3>
									<p className="text-[9px] text-slate-400 font-bold mt-1 uppercase tracking-widest opacity-60">* Dựa trên lợi nhuận gộp danh sách đơn hàng đã chốt</p>
								</div>
							</div>
							<div className="overflow-x-auto">
								<table className="w-full text-left text-sm">
									<thead className="bg-[#FFFCEB] dark:bg-slate-800/80 text-[9px] font-black text-slate-500 uppercase tracking-[2px] text-center">
										<thead className="bg-[#FFFCEB] dark:bg-slate-800/80 text-[9px] font-black text-slate-500 uppercase tracking-[2px] text-center">
											<tr>
												<th className="px-8 py-5 text-left w-[25%] font-black uppercase">Nhân viên & Sản phẩm</th>
												<th className="px-6 py-5 font-black uppercase">Thực bán</th>
												<th className="px-6 py-5 font-black uppercase">Giá Bán TB</th>
												{isAdmin && (
													<>
														<th className="px-6 py-5 font-black uppercase">LN Gộp / SP</th>
														<th className="px-6 py-5 font-black uppercase">Tổng LN</th>
													</>
												)}
												<th className="px-6 py-5 font-black uppercase">Chiết khấu</th>
												<th className="px-8 py-5 text-right font-black uppercase">Hoa hồng</th>
											</tr>
										</thead>
									</thead>
									<tbody className="divide-y divide-slate-50 dark:divide-slate-800">
										{staffs.filter(s => isAdmin || s.id === currentUserId).map(s => {
											const staffOrders = filteredOrders.filter(o => o.createdBy === s.id && o.status === 'Đơn chốt');
											const plan = kpiPlans.find(p => p.userId === s.id && p.month === fromDate.slice(0, 7));

											const productSummary: any = {};
											staffOrders.forEach(o => {
												(o.items || []).forEach((item: any) => {
													// Robust SKU/Key resolution for historical data
													const sku = item.sku || products.find(p => p.id === item.id)?.sku;
													const key = sku || item.id || item.name || 'OTHER';

													if (!productSummary[key]) {
														const pData = products.find(p => (sku && p.sku === sku) || (item.id && p.id === item.id));
														productSummary[key] = {
															key: key,
															name: item.name || pData?.name || 'Sản phẩm khác',
															sku: sku || 'N/A',
															qty: 0,
															totalRevenue: 0,
															totalCost: 0
														};
													}
													const itemBuyPrice = Number(item.buyPrice || products.find(p => p.id === item.id)?.priceBuy || 0);
													productSummary[key].qty += Number(item.qty) || 0;
													productSummary[key].totalRevenue += (Number(item.price) || 0) * (Number(item.qty) || 0);
													productSummary[key].totalCost += itemBuyPrice * (Number(item.qty) || 0);
												});
											});

											const items = Object.values(productSummary);
											if (items.length === 0) return null;

											return (
												<React.Fragment key={s.id}>
													<tr className="bg-slate-50/40 dark:bg-slate-800/20">
														<td colSpan={7} className="px-8 py-4">
															<div className="flex items-center gap-3">
																<div className="size-8 rounded-2xl bg-indigo-100 dark:bg-indigo-900/40 text-indigo-600 flex items-center justify-center font-black text-xs shadow-sm">
																	{s.displayName?.[0].toUpperCase()}
																</div>
																<span className="text-xs font-black text-slate-900 dark:text-white uppercase tracking-tight">{s.displayName}</span>
															</div>
														</td>
													</tr>
													{items.map((item: any) => {
														const avgPrice = item.qty > 0 ? item.totalRevenue / item.qty : 0;
														const avgBuyPrice = item.qty > 0 ? item.totalCost / item.qty : 0;
														const profitPerUnit = avgPrice - avgBuyPrice;
														const totalProfit = item.totalRevenue - item.totalCost;
														// Use the same robust key resolution as defined in productSummary
														const commissionKey = item.sku !== 'N/A' ? item.sku : item.name;
														const discountRate = plan?.productCommissions?.[commissionKey] || 0;
														const commissionAmount = totalProfit * (discountRate / 100);

														return (
															<tr key={item.key} className="hover:bg-slate-50 dark:hover:bg-slate-800/40 transition-all group">
																<td className="px-10 py-4">
																	<p className="text-[11px] font-black text-slate-700 dark:text-slate-300 uppercase leading-snug group-hover:text-indigo-600 transition-colors">{item.name}</p>
																	<p className="text-[8px] text-slate-400 font-bold uppercase tracking-widest">{item.sku}</p>
																</td>
																<td className="px-6 py-4 text-center">
																	<span className="text-xs font-black text-indigo-600 bg-indigo-50/50 dark:bg-indigo-900/20 px-2.5 py-1 rounded-lg">
																		{item.qty}
																	</span>
																</td>
																<td className="px-6 py-4 text-center font-bold text-slate-600 dark:text-slate-400">{formatPrice(avgPrice)}</td>
																{isAdmin && (
																	<>
																		<td className={`px-6 py-4 text-center font-bold ${profitPerUnit > 0 ? 'text-emerald-500' : 'text-rose-400'}`}>
																			{formatPrice(profitPerUnit)}
																		</td>
																		<td className="px-6 py-4 text-center font-black text-slate-900 dark:text-white">{formatPrice(totalProfit)}</td>
																	</>
																)}
																<td className="px-6 py-4 text-center">
																	<span className="px-3 py-1 bg-amber-50 dark:bg-amber-900/20 text-amber-600 rounded-full text-[10px] font-black border border-amber-100/50 dark:border-amber-900/20">
																		{discountRate}%
																	</span>
																</td>
																<td className="px-8 py-4 text-right font-black text-orange-500 text-sm">{formatPrice(commissionAmount)}</td>
															</tr>
														);
													})}
												</React.Fragment>
											);
										})}
									</tbody>
								</table>
							</div>
						</div>

						{/* Table 2: Bảng theo dõi KPI nhân sự */}
						<div className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-100 dark:border-slate-800 shadow-sm overflow-hidden mt-8">
							<div className="p-8 border-b border-slate-50 dark:border-slate-800 flex justify-between items-center bg-slate-50/20">
								<div>
									<h3 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-tight">Theo dõi chỉ tiêu (KPI)</h3>
									<p className="text-[9px] text-slate-400 font-bold mt-1 uppercase tracking-widest opacity-60">* Tự động đánh giá hiệu quả dựa trên hoạt động trực tế</p>
								</div>
								<div className="flex items-center gap-2 bg-white dark:bg-slate-800 px-3 py-1.5 rounded-xl border border-slate-100 dark:border-slate-700 shadow-sm">
									<Calendar size={12} className="text-slate-400" />
									<span className="text-[10px] font-black text-slate-500 uppercase">{fromDate} - {toDate}</span>
								</div>
							</div>
							<div className="overflow-x-auto">
								<table className="w-full text-left text-sm">
									<thead className="bg-[#EEF1FF] dark:bg-slate-800/80 text-[9px] font-black text-indigo-500 uppercase tracking-[2px] text-center">
										<tr>
											<th className="px-8 py-5 text-left font-black">Nhân viên</th>
											<th className="px-6 py-5 font-black">Check-in</th>
											<th className="px-6 py-5 font-black">Chấm công</th>
											<th className="px-6 py-5 font-black">Khách mới</th>
											<th className="px-6 py-5 font-black whitespace-nowrap">Tổng thực hiện</th>
											<th className="px-6 py-5 font-black">% Hoàn thành</th>
											<th className="px-8 py-5 font-black uppercase">Hành động</th>
										</tr>
									</thead>
									<tbody className="divide-y divide-slate-50 dark:divide-slate-800">
										{staffs.filter(s => isAdmin || s.id === currentUserId).map(s => {
											const plan = kpiPlans.find(p => p.userId === s.id && p.month === fromDate.slice(0, 7));

											const actualCheckins = checkins.filter(c => c.userId === s.id && filterByDate(c.createdAt)).length;
											const actualAttendance = attendanceLogs.filter(a => a.userId === s.id && a.date >= fromDate && a.date <= toDate && a.checkInAt).length;
											const actualNewCustomers = customers.filter(c => c.createdBy === s.id && c.createdAt && filterByDate(c.createdAt)).length;

											const targets = {
												checkin: plan?.checkinTarget || 1,
												attendance: plan?.attendanceTarget || 1,
												newCustomer: plan?.newCustomerTarget || 1
											};

											const rates = {
												checkin: (actualCheckins / targets.checkin) * 100,
												attendance: (actualAttendance / targets.attendance) * 100,
												newCustomer: (actualNewCustomers / targets.newCustomer) * 100
											};

											const avgCompletion = (Math.min(100, rates.checkin) + Math.min(100, rates.attendance) + Math.min(100, rates.newCustomer)) / 3;

											return (
												<tr key={s.id} className="hover:bg-slate-50 dark:hover:bg-slate-800 transition-all duration-300">
													<td className="px-8 py-5">
														<p className="text-xs font-black text-slate-900 dark:text-white uppercase leading-snug tracking-tight">{s.displayName}</p>
														<p className="text-[9px] font-bold text-slate-400 opacity-60">{s.email}</p>
													</td>
													<td className="px-6 py-5 text-center">
														<div className="flex flex-col items-center gap-1.5">
															<p className="text-xs font-black text-indigo-600">{actualCheckins} / {targets.checkin}</p>
															<div className="w-24 h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden shadow-inner">
																<div className="h-full bg-indigo-500 rounded-full transition-all duration-1000" style={{ width: `${Math.min(100, rates.checkin)}%` }}></div>
															</div>
														</div>
													</td>
													<td className="px-6 py-5 text-center">
														<div className="flex flex-col items-center gap-1.5">
															<p className="text-xs font-black text-emerald-600">{actualAttendance} / {targets.attendance}</p>
															<div className="w-24 h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden shadow-inner">
																<div className="h-full bg-emerald-500 rounded-full transition-all duration-1000" style={{ width: `${Math.min(100, rates.attendance)}%` }}></div>
															</div>
														</div>
													</td>
													<td className="px-6 py-5 text-center">
														<div className="flex flex-col items-center gap-1.5">
															<p className="text-xs font-black text-orange-600">{actualNewCustomers} / {targets.newCustomer}</p>
															<div className="w-24 h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden shadow-inner">
																<div className="h-full bg-orange-500 rounded-full transition-all duration-1000" style={{ width: `${Math.min(100, rates.newCustomer)}%` }}></div>
															</div>
														</div>
													</td>
													<td className="px-6 py-5 text-center">
														<span className="inline-flex size-8 items-center justify-center rounded-xl bg-slate-50 dark:bg-slate-800 text-xs font-black text-slate-700 dark:text-slate-300 shadow-sm border border-slate-100 dark:border-slate-700">
															{(actualCheckins + actualAttendance + actualNewCustomers)}
														</span>
													</td>
													<td className="px-6 py-5 text-center">
														<div className="flex flex-col items-center gap-2">
															<div className="relative size-12 flex items-center justify-center">
																<svg className="size-full -rotate-90" viewBox="0 0 36 36">
																	<circle cx="18" cy="18" r="16" fill="none" className="stroke-slate-100 dark:stroke-slate-800" strokeWidth="3"></circle>
																	<circle cx="18" cy="18" r="16" fill="none" className={`transition-all duration-1000 ${avgCompletion >= 100 ? 'stroke-emerald-500' : 'stroke-indigo-500'}`} strokeWidth="3" strokeDasharray="100" strokeDashoffset={100 - Math.min(100, avgCompletion)} strokeLinecap="round"></circle>
																</svg>
																<span className={`absolute text-[9px] font-black ${avgCompletion >= 100 ? 'text-emerald-600' : 'text-indigo-600'}`}>{avgCompletion.toFixed(0)}%</span>
															</div>
														</div>
													</td>
													<td className="px-8 py-5 text-center">
														{isAdmin ? (
															<button
																onClick={() => openKPIDialog(s)}
																className="size-9 bg-white dark:bg-slate-800 text-slate-400 hover:text-indigo-600 hover:border-indigo-100 rounded-xl transition-all border border-slate-50 dark:border-slate-700 shadow-sm flex items-center justify-center"
															>
																<Settings2 size={16} />
															</button>
														) : (
															<span className="text-[10px] font-black text-slate-300 uppercase tracking-widest italic">Cá nhân</span>
														)}
													</td>
												</tr>
											);
										})}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				)}
			</main>

			{/* MODAL GHI CHÚ THU CHI */}
			{
				showLogForm && (
					<div className="fixed inset-0 z-50 bg-[#1A237E]/80 backdrop-blur-sm flex items-center justify-center p-4">
						<div className="bg-white dark:bg-slate-900 w-full max-w-md rounded-[2.5rem] shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
							<div className="px-8 py-6 bg-indigo-600 text-white flex items-center justify-between">
								<h3 className="text-xl font-black uppercase tracking-tight">Ghi chú Thu / Chi</h3>
								<button onClick={() => {
									setShowLogForm(false);
									setSearchParams(prev => {
										prev.delete('new');
										return prev;
									});
								}} className="text-white/60 hover:text-white transition-colors text-3xl font-light">&times;</button>
							</div>
							<form onSubmit={handleAddLog} className="p-8 space-y-5">
								<div className="flex bg-slate-50 dark:bg-slate-800 p-1 rounded-2xl">
									<button
										type="button"
										onClick={() => setLogData({ ...logData, type: 'thu', category: 'Vay ngân hàng' })}
										className={`flex-1 py-3 rounded-xl text-xs font-black uppercase transition-all ${logData.type === 'thu' ? 'bg-white dark:bg-slate-700 text-emerald-600 shadow-sm' : 'text-slate-400'}`}
									>
										Thu vào (+)
									</button>
									<button
										type="button"
										onClick={() => setLogData({ ...logData, type: 'chi', category: 'Vận hành' })}
										className={`flex-1 py-3 rounded-xl text-xs font-black uppercase transition-all ${logData.type === 'chi' ? 'bg-white dark:bg-slate-700 text-rose-600 shadow-sm' : 'text-slate-400'}`}
									>
										Chi ra (-)
									</button>
								</div>

								<div>
									<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Số tiền (VNĐ)</label>
									<input
										type="number"
										className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 font-black text-indigo-600 text-lg focus:ring-2 focus:ring-indigo-500/20"
										placeholder="0"
										value={logData.amount === 0 ? '' : logData.amount}
										onChange={(e) => setLogData({ ...logData, amount: parseFloat(e.target.value) || 0 })}
										required
									/>
								</div>

								<div className="grid grid-cols-2 gap-4">
									<div>
										<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Hạng mục</label>
										<select
											className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-indigo-500/20 appearance-none"
											value={logData.category}
											onChange={(e) => setLogData({ ...logData, category: e.target.value })}
										>
											{logData.type === 'thu' ? (
												<>
													<option value="Vay ngân hàng">Vay ngân hàng</option>
													<option value="Vay khác">Vay khác</option>
													<option value="Tiền dư sẵn">Tiền dư sẵn</option>
													<option value="Khác">Khác</option>
												</>
											) : (
												<>
													<option value="Vận hành">Vận hành</option>
													<option value="Nhập hàng">Nhập hàng</option>
													<option value="Lương">Lương</option>
													<option value="Lãi suất ngân hàng">Lãi suất ngân hàng</option>
													<option value="Nợ gốc ngân hàng">Nợ gốc ngân hàng</option>
													<option value="Đáo hạn ngân hàng">Đáo hạn ngân hàng</option>
													<option value="Khác">Khác</option>
												</>
											)}
										</select>
									</div>
									<div>
										<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Ngày tháng</label>
										<input
											type="date"
											className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-indigo-500/20 text-slate-900 dark:text-white"
											value={logData.date}
											onChange={(e) => setLogData({ ...logData, date: e.target.value })}
										/>
									</div>
								</div>
								{logData.type === 'thu' && (logData.category === 'Vay ngân hàng' || logData.category === 'Vay khác') && (
									<div className="space-y-4 animate-in slide-in-from-top-2 duration-200">
										<div className="grid grid-cols-2 gap-4">
											{logData.category === 'Vay ngân hàng' && (
												<div>
													<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Ngân hàng</label>
													<select
														className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-indigo-500/20"
														value={logData.bankName}
														onChange={(e) => setLogData({ ...logData, bankName: e.target.value })}
													>
														<option value="">-- Chọn ngân hàng --</option>
														{BANKS.map(b => <option key={b} value={b}>{b}</option>)}
													</select>
												</div>
											)}
											<div className={logData.category !== 'Vay ngân hàng' ? 'col-span-2' : ''}>
												<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Kỳ hạn vay</label>
												<select
													className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-indigo-500/20"
													value={logData.loanTerm}
													onChange={(e) => setLogData({ ...logData, loanTerm: e.target.value })}
												>
													<option value="">-- Chọn kỳ hạn --</option>
													{LOAN_TERMS.map(t => <option key={t} value={t}>{t}</option>)}
												</select>
											</div>
										</div>

										<div>
											<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Lãi suất (% / năm)</label>
											<div className="flex gap-2">
												<div className="relative flex-1">
													<input
														type="number"
														step="0.1"
														className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 font-black text-indigo-600 focus:ring-2 focus:ring-indigo-500/20"
														placeholder="0.0"
														value={logData.interestRate === 0 ? '' : logData.interestRate}
														onChange={(e) => setLogData({ ...logData, interestRate: parseFloat(e.target.value) || 0 })}
													/>
												</div>
												{logData.category === 'Vay ngân hàng' && (
													<button
														type="button"
														onClick={handleAIInterestRate}
														disabled={isFetchingRate || !logData.bankName || !logData.loanTerm}
														className="px-6 rounded-2xl bg-indigo-50 dark:bg-indigo-900/40 text-indigo-600 dark:text-indigo-400 hover:bg-indigo-100 transition-all disabled:opacity-50 flex items-center gap-2 font-black text-[10px] uppercase shadow-sm border border-indigo-100 dark:border-indigo-800"
													>
														{isFetchingRate ? <Sparkles className="animate-spin text-indigo-400" size={14} /> : <Bot size={16} />}
														Tra cứu
													</button>
												)}
											</div>
										</div>
									</div>
								)}

								<div>
									<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Email (Nếu có)</label>
									<input
										type="email"
										className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-indigo-500/20 text-slate-900 dark:text-white"
										placeholder="example@mail.com"
										value={logData.email}
										onChange={(e) => setLogData({ ...logData, email: e.target.value })}
									/>
								</div>

								{logData.type === 'chi' && ['Lãi suất ngân hàng', 'Nợ gốc ngân hàng', 'Đáo hạn ngân hàng'].includes(logData.category) && (
									<div className="animate-in slide-in-from-top-2 duration-200">
										<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Chọn khoản vay liên quan</label>
										<select
											className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-indigo-500/20 text-indigo-600"
											value={logData.parentId}
											onChange={(e) => {
												const selectedLoan = cashLogs.find(l => l.id === e.target.value);
												setLogData({ 
													...logData, 
													parentId: e.target.value,
													amount: logData.category !== 'Lãi suất ngân hàng' ? (selectedLoan?.amount || 0) : logData.amount,
													email: selectedLoan?.email || logData.email
												});
											}}
											required
										>
											<option value="">-- Chọn khoản vay để tất toán/đóng lãi --</option>
											{cashLogs.filter(l => l.type === 'thu' && l.category === 'Vay ngân hàng').map(loan => {
												const isPaid = cashLogs.some(l => l.parentId === loan.id && (l.category === 'Nợ gốc ngân hàng' || l.category === 'Đáo hạn ngân hàng'));
												return (
													<option key={loan.id} value={loan.id} disabled={isPaid}>
														{loan.bankName} - {formatPrice(loan.amount)} ({loan.date}) {isPaid ? '[ĐÃ TẤT TOÁN]' : ''}
													</option>
												);
											})}
										</select>
										<p className="mt-2 text-[9px] text-slate-400 font-bold uppercase ml-1 opacity-70">* Phải chọn đúng khoản vay để Bot tính lãi chính xác</p>
									</div>
								)}

								<div>
									<div className="flex items-center justify-between mb-2 ml-1">
										<label className="block text-[10px] font-black text-slate-400 uppercase">Ghi chú chi tiết</label>
										{logData.type === 'thu' && (logData.category === 'Vay ngân hàng' || logData.category === 'Vay khác') && (
											<button
												type="button"
												onClick={handleAILoanAnalysis}
												disabled={isFetchingRate}
												className="flex items-center gap-1.5 text-[9px] font-black text-indigo-600 hover:text-indigo-700 bg-indigo-50 dark:bg-indigo-900/30 px-2.5 py-1 rounded-lg transition-all"
											>
												<Sparkles size={10} />
												TẠO GHI CHÚ AI
											</button>
										)}
									</div>
									<textarea
										className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 text-sm font-medium focus:ring-2 focus:ring-indigo-500/20 resize-none h-24"
										placeholder="VD: Chi tiền điện nước tháng 1..."
										value={logData.note}
										onChange={(e) => setLogData({ ...logData, note: e.target.value })}
									/>
								</div>

								<button
									type="submit"
									className="w-full bg-indigo-600 text-white py-4 rounded-2xl font-black uppercase tracking-widest shadow-xl shadow-indigo-500/20 hover:bg-indigo-700 transition-all active:scale-95"
								>
									Xác nhận ghi sổ
								</button>
							</form>
						</div>
					</div>
				)
			}
			{/* MODAL LẬP KẾ HOẠCH KPI */}
			{
				showPlanForm && selectedStaffForPlan && (
					<div className="fixed inset-0 z-[60] bg-[#1A237E]/80 backdrop-blur-sm flex items-center justify-center p-4">
						<div className="bg-white dark:bg-slate-900 w-full max-w-xl rounded-[2.5rem] shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
							<div className="px-8 py-6 bg-indigo-600 text-white flex items-center justify-between">
								<div className="flex items-center gap-3">
									<Target size={24} />
									<div>
										<h3 className="text-xl font-black uppercase tracking-tight">Kế hoạch KPI Tháng {fromDate.slice(0, 7)}</h3>
										<p className="text-xs font-bold opacity-60 uppercase">{selectedStaffForPlan.displayName}</p>
									</div>
								</div>
								<button onClick={() => setShowPlanForm(false)} className="text-white/60 hover:text-white transition-colors text-3xl font-light">&times;</button>
							</div>
							<div className="p-8 space-y-6 max-h-[70vh] overflow-y-auto custom-scrollbar">
								<div className="grid grid-cols-2 gap-4">
									<div>
										<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Lương cứng cơ bản (VNĐ)</label>
										<input
											type="number"
											className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 font-black text-indigo-600 focus:ring-2 focus:ring-indigo-500/20"
											value={planData.baseSalary}
											onChange={(e) => setPlanData({ ...planData, baseSalary: parseFloat(e.target.value) || 0 })}
										/>
									</div>
									<div>
										<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Chỉ tiêu Check-in (Lượt)</label>
										<input
											type="number"
											className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 font-black text-purple-600 focus:ring-2 focus:ring-indigo-500/20"
											value={planData.checkinTarget}
											onChange={(e) => setPlanData({ ...planData, checkinTarget: parseInt(e.target.value) || 0 })}
										/>
									</div>
								</div>

								<div className="grid grid-cols-2 gap-4">
									<div>
										<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Chỉ tiêu Chấm công (Ngày)</label>
										<input
											type="number"
											className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 font-black text-emerald-600 focus:ring-2 focus:ring-indigo-500/20"
											value={planData.attendanceTarget}
											onChange={(e) => setPlanData({ ...planData, attendanceTarget: parseInt(e.target.value) || 0 })}
										/>
									</div>
									<div>
										<label className="block text-[10px] font-black text-slate-400 uppercase mb-2 ml-1">Chỉ tiêu Khách mới</label>
										<input
											type="number"
											className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-4 font-black text-orange-600 focus:ring-2 focus:ring-indigo-500/20"
											value={planData.newCustomerTarget}
											onChange={(e) => setPlanData({ ...planData, newCustomerTarget: parseInt(e.target.value) || 0 })}
										/>
									</div>
								</div>

								<div className="space-y-4">
									<div className="flex items-center justify-between">
										<label className="block text-[10px] font-black text-slate-400 uppercase ml-1">Chiết khấu theo Sản phẩm (%)</label>
										<p className="text-[9px] font-bold text-slate-400 italic">* % Hoa hồng tính trên Lợi nhuận gộp</p>
									</div>

									<div className="space-y-3 bg-slate-50 dark:bg-slate-800/50 p-4 rounded-[2rem]">
										{(() => {
											const staffOrders = orders.filter(o => o.createdBy === selectedStaffForPlan.id && o.status === 'Đơn chốt');

											// Generate a unique list of sold products with their best available key (SKU or Name)
											const soldProductMap: Record<string, { name: string, sku: string }> = {};
											staffOrders.forEach(o => {
												(o.items || []).forEach((item: any) => {
													const sku = item.sku || products.find(p => p.id === item.id)?.sku || 'N/A';
													const key = sku !== 'N/A' ? sku : item.name;
													if (!soldProductMap[key]) {
														soldProductMap[key] = { name: item.name, sku: sku };
													}
												});
											});

											const soldProductList = Object.entries(soldProductMap);

											if (soldProductList.length === 0) return <p className="text-[10px] text-slate-400 italic text-center py-4">Nhân viên chưa bán sản phẩm nào trong kỳ.</p>;

											return soldProductList.map(([key, data]) => {
												return (
													<div key={key} className="flex items-center justify-between gap-4 p-3 bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-50 dark:border-slate-700">
														<div className="flex-1 overflow-hidden">
															<p className="text-[10px] font-black text-slate-800 dark:text-white truncate uppercase leading-tight">{data.name}</p>
															<p className="text-[8px] font-bold text-slate-400 uppercase tracking-widest">{data.sku}</p>
														</div>
														<div className="w-24">
															<div className="relative">
																<input
																	type="number"
																	step="0.1"
																	className="w-full bg-slate-50 dark:bg-slate-700 border-none rounded-lg px-3 py-2 text-xs font-black text-indigo-600 focus:ring-2 focus:ring-indigo-500/20 pr-6"
																	placeholder="0"
																	value={planData.productCommissions[key] ?? ''}
																	onChange={(e) => {
																		const val = e.target.value;
																		const rate = val === '' ? 0 : parseFloat(val);
																		setPlanData({
																			...planData,
																			productCommissions: { ...planData.productCommissions, [key]: rate }
																		});
																	}}
																/>
																<span className="absolute right-2 top-1/2 -translate-y-1/2 text-[10px] font-black text-slate-400">%</span>
															</div>
														</div>
													</div>
												);
											});
										})()}
									</div>
								</div>
							</div>
							<div className="p-8 bg-slate-50 dark:bg-slate-800/50 flex gap-4">
								<button
									onClick={() => setShowPlanForm(false)}
									className="flex-1 py-4 rounded-2xl font-black text-xs uppercase tracking-widest text-slate-400 hover:text-slate-600 transition-all"
								>
									Hủy bỏ
								</button>
								<button
									onClick={handleSaveKPIPlan}
									className="flex-[2] bg-indigo-600 text-white py-4 rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl shadow-indigo-500/20 hover:bg-indigo-700 transition-all"
								>
									Lưu kế hoạch tháng
								</button>
							</div>
						</div>
					</div>
				)
			}

			{/* Popup hiển thị chi tiết nội dung */}
			{selectedNote && (
				<div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
					<div 
						className="bg-white dark:bg-slate-900 w-full max-w-lg rounded-3xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200"
						onClick={(e) => e.stopPropagation()}
					>
						<div className="p-6 border-b border-slate-50 dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-800/50">
							<h3 className="text-sm font-black uppercase tracking-widest text-slate-400">Chi tiết ghi chú</h3>
							<button 
								onClick={() => setSelectedNote(null)}
								className="size-8 flex items-center justify-center rounded-full hover:bg-white dark:hover:bg-slate-800 text-slate-400 hover:text-slate-600 transition-all"
							>
								<span className="material-symbols-outlined text-xl">close</span>
							</button>
						</div>
						<div className="p-8">
							<div className="bg-slate-50 dark:bg-slate-800/30 p-6 rounded-2xl border border-slate-100 dark:border-slate-700/50">
								<p className="text-slate-700 dark:text-slate-200 leading-relaxed whitespace-pre-wrap font-medium">
									{selectedNote}
								</p>
							</div>
						</div>
						<div className="p-6 bg-slate-50/50 dark:bg-slate-800/50 flex justify-end">
							<button
								onClick={() => setSelectedNote(null)}
								className="px-8 py-3 bg-indigo-600 text-white rounded-xl font-black text-[10px] uppercase tracking-widest shadow-lg shadow-indigo-500/20 active:scale-95 transition-all"
							>
								Đóng lại
							</button>
						</div>
					</div>
					<div className="absolute inset-0 -z-10" onClick={() => setSelectedNote(null)} />
				</div>
			)}
		</div >
	);
};

export default Finance;
